### ISSUE TITLE
如何 让 网页不是在 http:localhost 运行 ，而是在 http:localhost:3005

### ISSUE THREAD

**Issue by tomridder** [yakami129/VirtualWife#83]
如果想让 网页不是在 http:localhost 运行 ，而是在 http:localhost:3005

是不是要更改 /root/VirtualWife/domain-chatvrm/ 下 的package.json文件呢

[root@RainYun-ZDgShJEh domain-chatvrm]# cat package.json 
{
  "name": "chat-vrm",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev -p 3005",
    "build": "next build",
    "build:with-lint": "npm run build && npm run lint",
    "start": "next start -p 3005",
    "export": "next export",
    "lint": "next lint"
  },

====================

**Comment by yakami129** [comment]
使用docker部署，只需要更改docker-compose.yaml
```
......
 gateway:
   container_name: gateway
   image: okapi0129/virtualwife-gateway:${GATEWAY_TAG:-latest}
   restart: always
   ports:
     - ${NGINX_HTTP_PORT:-80}:80  改成：3005:80
......
```
如果是源码方式，可以按照你的方式更改
